name: Deploy to Neocities

on:
  push:
    branches:
      - main  # or 'master' depending on your default branch name

concurrency:
  group: deploy-to-neocities
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to Neocities
        uses: b3nj5m1n/deploy-to-neocities-action@v1
        with:
          api_token: ${{ secrets.NEOCITIES_API_TOKEN }}
          cleanup: true
          dist_dir: public
